#define ASSETS_PATH "../assets"
#define MAP_PATH "../ressources"
#define CHARACTER_ASSETS_PATH ASSETS_PATH "/characters"
#define GUI_ASSETS_PATH ASSETS_PATH "/GUI"
#define TIME_SHOOT_TO_IDLE 0.5f
#define TIME_BETWEEN_ANIMATIONS 0.4f
#define WINDOW_WIDTH 1080
#define WINDOW_HEIGHT 680
#define CAMERA_WIDTH 400.f
#define CAMERA_HEIGHT 250.f

